---
title: "DID_Tina"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(magrittr)
library(ggplot2)
load(url("https://github.com/tpemartin/Econometric-Analysis/blob/master/data/public.rda?raw=true"))
```


```{r}
public %>% select(EMPFT,EMPPT,EMPFT2,EMPPT2)
#看有興趣的變數，發現這些變數被當作是字串("chr")，則無法運算，故需要改變資料屬by mutate以轉換成數值
```

```{r}
public %>%
  mutate_at(
    vars(EMPFT,EMPPT,EMPFT2,EMPPT2),
    list(as.numeric)
    ) -> public  
```

```{r}
#不同政策州的前後 (before/after)
#計算平均員工數
#利用州是否為1或0分兩群：group_by
#分完群之後再計算"平均"(summarise)
public %>% 
  group_by(STATE) %>% # 1 if NJ; 0 if Pa
  summarise(mFT_before=mean(EMPFT,na.rm=T),
            mPT_before=mean(EMPPT,na.rm=T),
            mFT_after=mean(EMPFT2,na.rm=T),
            mPT_after=mean(EMPPT2,na.rm=T)) %>%
  ungroup ->
  employment_change
#四個變數求取mean
#group_by結束後要ungroup
#計算結果存在employment_change
```

```{r}
employment_change
```

```{r}
#查看全職員工數
library(kableExtra)
employment_change %>% 
  select(STATE,mFT_before,mFT_after) %>%
  kable("html")
#kable("html"):生成網頁形式
#employment_change有八個結果，只選了state中的mFT_before,mFT_after作0呈現

##結果呈現：在政策實行前，NJ的雇用量較低；政策實行後，NJ雇用量上升，但不代表是最低工資促進就業上升的政策效果，故選擇PA來了解是否是大環境(非政策效果)變好的影響，但可能會發現大環境是變差，因為PA的雇用量下降，表示PA不但沒有因為最低工資提高而使就業量上升，而且PA沒有最低工資的變化，但卻使就業量更低
```

```{r}
#查看兼職員工數
employment_change %>% 
  select(STATE,mPT_before,mPT_after) %>%
  kable("html")
```

## 8-4繪圖

```{r}
library(tidyr)
```

```{r}
#只看全職員工數
employment_FTchange <- employment_change %>%
  select(mFT_before,mFT_after,STATE)

employment_FTchange %>% kable("html")
```

```{r}
employment_FTchange %>% 
  filter(STATE==0) %>%
  gather(type,employment,-STATE) -> EMFT0
EMFT0

employment_FTchange %>% 
  filter(STATE==1) %>%
  gather(type,employment,-STATE) -> EMFT1
EMFT1

EMFT<-rbind(EMFT0,EMFT1)
EMFT
```

```{r}
EMFT %>% 
  ggplot() +
  geom_point(aes(x=type,y=employment,color=STATE))+
  geom_line(aes(x=type,y=employment,group=STATE,color=STATE))
```

```{r}
#更改變數屬性
EMFT %>% mutate(
  type=ordered(type,levels=c("mFT_before","mFT_after")),
  STATE=factor(STATE,labels=c("PA","NJ"))
  ) -> EMFTfinal
```

```{r}
#修改屬性後的圖形
EMFTfinal %>% 
  ggplot() +
  geom_point(aes(x=type,y=employment,color=STATE))+
  geom_line(aes(x=type,y=employment,group=STATE,color=STATE))
```


## 迴歸模型


```{r}
#資料整理前的結果
public %>% select(STATE,EMPFT,EMPFT2)
#資料變數名稱要大寫
#想把EMPFT以及EMPFT2轉換成為EMPFT和t兩個column的變數 (一筆資料變成兩筆)
#每一筆資料依照變數名稱堆疊起來

#考試不考資料整理
```

資料整理
```{r}
#做DID，尚未控制任何變數
public %>% 
  select(STATE,EMPFT,EMPFT2) %>%
  group_by(STATE) %>%
  gather(type,emp,-STATE) -> public2

#資料整理完的結果
public2

#結果呈現：資料未處理前的EMPFT值直接堆疊至emp，新創的變數名稱為type，type裡面的所有變數都是EMPTF的堆疊，表示為最低工資提高前的值，後面堆疊的是EMPTF2的值一直堆疊下去
```

```{r}
head(public2)
#type有時間意涵，若變數為EMPFT則代表政策前，EMPFT2則代表政策後
```

產生虛擬變數
```{r}
#public2原本只有State type emp這三欄，創造新變數(dummy variable)
public2 %>%
  mutate(
    STATE1=(STATE==1),
    AFTER=(type=="EMPFT2"),
    PolicyImpact=STATE1*AFTER
  ) -> public2

public2

#創造state dummy：D1 (state1)
#政策後的dummy: (after)
#程式語言中，logical的True or False，若拿來當成數學運算，True會被當作1；False會被當作0來處理 (例:PolicyImpact的結果)
```

DD估計
```{r}
#產生D1(STATE1)和B1(AFTER)之後，進行線性回歸
lm(emp~STATE1+AFTER+PolicyImpact,data=public2)->DD_result
DD_result
#結果：最低工資的提高會造成每家餐廳全職就業量提升3.362個員工 -> 此結果有點不合理，表示有很多變數尚未被控制住
#缺點：lm跑出來的結果非調整後的標準誤差，而是古典假設的結果->處理cluster(聚類標準誤)之問題
```

```{r}
#若不先創造一個PolicyImpact，而選擇在回歸時才加入此變數，利用I()創造此變數
lm(emp~STATE1+AFTER+I(STATE1*AFTER),data=public2)
```


## factor()的應用

```{r}
lm(emp~factor(STATE)*factor(type),data=public2)
#在類別資料裡面，若不想要自己創造dummy variable，可使用factor()，讓程式自己判斷變數為"類別"
```

factor()應用的例子
```{r}
lm(emp~STATE1+AFTER,data=public2)
#若沒特別說明，則此回歸會包含beta_0
#創dummy variables是為了分類
```


```{r}
#和程式R講說此兩個變數(STATE以及TYPE)是用來分類:應用factor宣告
lm(emp~factor(STATE)+factor(type),data=public2)
#控制state和type
#跑出來的結果和#197的結果一樣，但#204的回歸變數是用來分類

#程式(R)只要知道其為"類別變數"，則程式會依據有幾類去做調整(電腦幫忙創造dummy variable之概念)
```


有交叉項
```{r}
#交叉相乘(用I()自己創造變數，兩個dummy交叉相乘，沒有factor宣告之情形)
lm(emp~STATE1+AFTER+I(STATE1*AFTER),data=public2)
#變數使用的是dummy varibale:STATE1以及AFTER
```


```{r}
lm(emp~factor(STATE)+factor(type)+factor(STATE):factor(type),data=public2)
#有factor宣告的兩個dummy交叉相乘，其符號為分號，而非兩個factor用乘號相乘在一起
#此時的兩個factor交叉相乘用分號(:)，而不是乘號(*)

#若factor用"乘號(*)"相乘，則表示個別效果再加上交叉相乘效果，例如lm(emp~factor(STATE)+factor(type)+factor(STATE):factor(type),data=public2)寫法會等同於lm(emp~factor(STATE)*factor(type),data=public2)

#變數使用的是尚未被分類的原本變數(非dummy，是利用factor宣告後才成為dummy):STATE以及TYPE
```

```{r}
#223的另種寫法
lm(emp~factor(STATE)*factor(type),data=public2)
```

聚類標準誤差
```{r}
library(clubSandwich)
#為了作"聚類標準誤"的套件
```

```{r}
public2 %>% 
  mutate(cluster=factor(STATE):factor(type)) -> public2
#群來自交叉項，故使用分號(:)????
```

```{r}
public2$cluster %>% class
public2$cluster %>% as.factor %>% levels
#交叉出四類可能組合，故不用自己創造dummy
```

```{r}
public2$cluster
```

```{r}
coef_test(DD_result, vcov = "CR2", cluster = public2$cluster)
#coeftesm來自於lmtest套件，coef_test來自clubsandwich套件，但兩者用法相同
#注意此處的coef_test有底線
#此處的Standard error才是正確的標準誤差，而係數不受standrd error(穩健度)調整的影響
```


```{r}

```










