---
title: "panel_tina"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(magrittr)
```

```{r}
library(readr)
fatality <- read_csv("https://raw.githubusercontent.com/tpemartin/Econometric-Analysis/master/Part%20II/fatality.csv")
#state:i
#i=1一組，i=4一組.....
#year:t
#變數有無下標it由data判斷，電腦不會主動告知
```

```{r}
library(plm)
```

```{r}
class(fatality)
#原本資料為dataframe，但dataframe沒有panel的概念，故要改變其類別
```

```{r}
pdf_fatality<-pdata.frame(fatality,c("state","year"))
#放入兩個變數名稱，第一個"state"為i，第二個"year"為t
```

```{r}
class(pdf_fatality)
#class要出現pdata.frame才可正確使用plm套件中的固定效果模型等等
```

```{r}
#各州啤酒稅（beertax）與車禍死亡率（mrall）
library(dplyr)
library(ggplot2)
pdf_fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000)))
#ggplot2:形成canvas(畫布)
#"+"：用加號做連結，表示加上層疊的圖形，以geom作開頭，在畫布上層疊不同的geometric objects(幾何圖形)
#aes：函數位置，X軸:data裡面的變數(beertax),Y軸:用I作變數值直接轉換；mutate(創造新變數)之概念
```

非mapping的color設定
```{r}
#把美學color="blue"放在aes外面
#非資料map出的顏色
library(dplyr)
library(ggplot2)
pdf_fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000)),color="blue")
#blue(顏色)是美學的點的元素
#顏色不寫在aes裡面表示，所有點都統一設定顏色
```

mapping的color設定
```{r}
#用顏色區分不同的州
#?ggplot ~美感
#stroke：圈，fill：圈裡面的填滿
#把美學color放在aes裡面(放在美學的map function)
library(dplyr)
library(ggplot2)
pdf_fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),color=state))
#color由資料map得來(內建模式)，所以顏色不是自己指定的，而是由資料變數本身的"值"所指定
```

mapping的color設定
```{r}
library(dplyr)
library(ggplot2)
pdf_fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),color=year))
```


```{r}
fatality$state %>% class
#"state"用數字區分為哪一州，所以state的class為num.
#class為數字(numeric)分兩種：1.integer 2.float(double)

#為何state的離散圖中其點的顏色會是漸層?
#因為state的class為"numeric"，表示資料為連續(非間斷)，例如1 1 1 4 4 4，故在資料視覺化時，顏色會用漸層上色
```

```{r}
library(dplyr)
library(ggplot2)
pdf_fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),color=as.factor(state)))
#若只改class，則變數不需使用"I()"
#factor表示"類別"，類別為"不連續"概念，故會使用間斷顏色->即使state原本為num.，但改變class後，則表示大小連續是用來"分類"用的
#num.時是用"顏色深淺"；factor是用"不同的顏色"，每一個顏色代表一個數字，中間無法連續
```

```{r}
#shape -> 間斷
#年份用不同形狀表示
library(dplyr)
library(ggplot2)
pdf_fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),shape=as.factor(year)))
```

```{r}
#不同年用不同顏色畫離散圖
#as.factor:class改為factor
library(dplyr)
library(ggplot2)
pdf_fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),color=as.factor(year)))
```

```{r}
#組內差異，進行demean
pdf_fatality %>% 
  group_by(state) %>% #依state分組進行以下程序：
  mutate(
    mrall_demean=mrall-mean(mrall),
    beertax_demean=beertax-mean(beertax)
    ) %>%
  select(mrall_demean,beertax_demean,state) %>%
  ungroup() -> demean_results
#grouping variable會被保留

#mutate:創造新變數->demean=原始變數資料-mean(變數資料)
#先(分組)group_up，才能進行mutate，因為要用的是組的mean，而非全體的mean
#group_by之後要記得ungroup，避免變數出現warning
```

```{r}
#Demean 之後再畫一次離散圖
# #133的結果存為demean_results，故資料來源data frame)為demean_results
demean_results %>%
  ggplot()+
  geom_point(aes(x=beertax_demean,y=mrall_demean,color=as.factor(state)))
```

```{r}
#demean前
pdf_fatality %>% 
  filter(state==40) %>%
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),color=as.factor(state)),size=5)
#size=5:不是透過mapping達到，用來放大點
```


```{r}
#demean後
demean_results %>%
  filter(state==40) %>%
  ggplot()+
  geom_point(aes(x=beertax_demean,y=I(mrall_demean*1000),color=as.factor(state)),size=5)
#size=5:不是透過mapping達到，用來放大點
#(0,0)是demean後離散圖的中心點
```

```{r}
demean_results %>%
  ggplot()+
  geom_point(aes(x=beertax_demean,y=mrall_demean,color=as.factor(state)))+
  geom_smooth(aes(x=beertax_demean,y=mrall_demean),method = "lm",se=FALSE)
#se：standard error，TRUE:95%信賴區間，其中TRUE或FALSE是全大寫
```

```{r}
pdf_fatality %>% lm(data=., mrall~factor(state)) -> results
# results$residuals 也會是demean的結果
```

# 資料分析流程
## 確定變數class
```{r}
pdf_fatality %>% 
  mutate(state=as.factor(state),year=as.orered(year)) -> fatality
#用mutate修正class，並存下來
#之後再開始作圖及資料分析，這樣就不用在過程中一直處理轉換class的問題
```

##作圖

##資料分析
```{r}
ls(mrall~beetrax+state, date=pdf_fatality)
```


```{r}
model<-mrall~beertax
```

## plm

```{r}
pool1<-plm(model, data=pdf_fatality, model='pooling')
summary(pool1)
```


```{r}
re1<-plm(model, data=pdf_fatality, model='random')
summary(re1)
```

```{r}
fe1<-plm(model, data=pdf_fatality, model='within', effect='individual')
summary(fe1)
```

```{r}
fe2<-plm(model, data=pdf_fatality, model='within', effect='twoways')
summary(fe2)
```

```{r, results="asis"}
library(stargazer)
stargazer(pool1,re1,fe1,fe2,type='html',
          column.labels = c("Pooled OLS","RE","FE-individual","FE-two-ways"))
#用stargazer作模型比較
```

```{r}
phtest(fe1,re1)
#在虛無假設(H_0)下，V_it與beertax_it無關 -> 可用FE、RE
#在對立假設(H_1)下 -> 只可用 FE?
```

```{r}
pdf_fatality %>%
  plm(mrall~beertax+unrate, data=., method="within",effect = "individual")
```












