---
title: "R for TSLS"
author: "姓名"
date: "3/6/2019"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=T)
library(dplyr)
library(magrittr)
library(AER)
data("CigarettesSW")
```



```{r}
CigarettesSW %<>% as_tibble
CigarettesSW
```

```{r}
CigarettesSW %<>% filter(year=="1995")
```

```{r}
CigarettesSW %<>% 
  mutate(
    rprice=price/cpi,
    rincome=income/population/cpi,
    tdiff=(taxs-tax)/cpi
  )
```

```{r}
model1 <- log(packs) ~ log(rprice) 
model2 <- log(packs) ~ log(rprice) + log(rincome)
```

```{r}
ols1<-lm(model1,CigarettesSW)
ols2<-lm(model2,CigarettesSW)

library(sandwich)
library(lmtest)
library(stargazer)

#使用vcovHC函數來計算HC1型的異質變異（即橫斷面資料下的線性迴歸模型）
coeftest(ols1, vcov. = vcovHC, type="HC1") -> ols1_coeftest
coeftest(ols2, vcov. = vcovHC, type="HC1") -> ols2_coeftest
```

```{r}

```






















